version: "3"

services:
    pp-react-nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/react-nginx/Dockerfile
            target: prod
        image: pp-react-nginx
        environment:
            - PORT=${REACT_PORT}
            - BROWSER=${REACT_BROWSER}
        ports:
            - 80:80
        depends_on:
            - pp-api
    pp-api:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        image: pp-api
        environment:
            - MONGODB_CONNECTION_STRING=${BACKEND_MONGODB_CONNECTION_STRING}
        expose:
            - 5000
        command: "npm start"
    pp-cron:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/cron/Dockerfile
        image: pp-cron