version: "3"

services:
    pp-nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: pp-nginx
        environment:
            - PORT=${NGINX_PORT}
            - BROWSER=${NGINX_BROWSER}
        ports:
            - 80:80
        depends_on:
            - pp-backend
    pp-backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        image: pp-backend
        environment:
            - MONGODB_CONNECTION_STRING=${BACKEND_MONGODB_CONNECTION_STRING}
        expose:
            - 3000
        command: "npm start"
