version: "3"

services:
    bp-react-nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/react-nginx/Dockerfile
            target: prod
        image: bp-react-nginx
        volumes:
            - bp-ssl-certificates:/etc/letsencrypt
        environment:
            - PORT=${REACT_PORT}
            - BROWSER=${REACT_BROWSER}
            - REACT_APP_HCAPTCHA_SITE_KEY=${REACT_HCAPTCHA_SITE_KEY}
        ports:
            - 80:80
            - 443:443
        depends_on:
            - bp-api
    bp-certbot:
        build:
            context: ./docker/certbot
            args: # This will make it into the /root/.secrets/cloudflare.ini file.
                - DNS_CLOUDFLARE_API_TOKEN=${CERTBOT_DNS_CLOUDFLARE_API_TOKEN}
        image: bp-certbot
        volumes:
            - bp-ssl-certificates:/etc/letsencrypt
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/cloudflare.ini --email contact@bullionpricer.com --agree-tos --no-eff-email -d bullionpricer.com --preferred-challenges dns-01 --dns-cloudflare-propagation-seconds 60 --non-interactive; sleep 12h & wait $${!}; done;'"
    bp-api:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        image: bp-api
        environment:
            - MONGODB_CONNECTION_STRING=${API_MONGODB_CONNECTION_STRING}
            - HCAPTCHA_SECRET_KEY=${API_HCAPTCHA_SECRET_KEY}
            - POSTMARK_SERVER_TOKEN=${API_POSTMARK_SERVER_TOKEN}
        expose:
            - 5000
        command: "npm start"
    bp-cron:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/cron/Dockerfile
        image: bp-cron
        environment:
            - MONGODB_CONNECTION_STRING=${API_MONGODB_CONNECTION_STRING}
            - CURRENCY_BEACON_API_TOKEN=${CRON_CURRENCY_BEACON_API_TOKEN}
            - SCRAPEOPS_API_KEY=${CRON_SCRAPEOPS_API_KEY}
            - BABEL_DISABLE_CACHE=1
            - DO_SCRAPING=${CRON_DO_SCRAPING}
    bp-product-scraper: #worker which registers itself with the bp-cron leader.
        build:
            context: .
            dockerfile: ./docker/product-scraper/Dockerfile
        image: bp-product-scraper
        environment:
            - LEADER_HOST=bp-cron
            - LEADER_PORT=8000
        expose:
            - 8000
        depends_on:
            - bp-cron #because bp-cron is our cluster leader.
    #Just for the time being we'll run the database in production. The only data that is permanent is user subscriptions (for now)
    bp-db:
        restart: unless-stopped
        build:
            context: ./docker/db
        image: bp-db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${DB_MONGO_INITDB_DATABASE}
        volumes:
            - bp-mongodb:/data/db
        expose:
            - 27017

volumes:
    bp-mongodb:
        name: bp-mongodb
    bp-ssl-certificates:
        name: bp-ssl-certificates