version: "3"

services:
    pp-react: #front-end web application
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/react-nginx/Dockerfile
            target: dev-react
        image: pp-react
        environment:
            - PORT=${REACT_PORT}
            - BROWSER=${REACT_BROWSER}
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_HCAPTCHA_SITE_KEY=${REACT_HCAPTCHA_SITE_KEY}
        volumes:
            - pp-react-node_modules:/app/react/node_modules
            - ./react:/app/react
        #Using ports instead of expose as CHOKIDAR_USEPOLLING (live code reloading) wouldn't work with nginx in front (was blocking port comms)
        ports:
            - 3000:3000
    pp-api: #the web application's api
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        image: pp-api
        environment:
            - MONGODB_CONNECTION_STRING=${API_MONGODB_CONNECTION_STRING}
            - HCAPTCHA_SECRET_KEY=${API_HCAPTCHA_SECRET_KEY}
            - POSTMARK_SERVER_TOKEN=${API_POSTMARK_SERVER_TOKEN}
        volumes:
            - pp-api-node_modules:/app/node_modules
            - ./api:/app
        expose:
            - 5000
        depends_on:
            - pp-db
        command: "npm start"
    pp-nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/react-nginx/Dockerfile
            target: dev-nginx
        image: pp-nginx
        ports:
            - 80:80
        depends_on:
            - pp-react
            - pp-api
    pp-db:
        restart: unless-stopped
        build:
            context: ./docker/db
        image: pp-db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${DB_MONGO_INITDB_DATABASE}
        volumes:
            - pp-mongodb:/data/db
        #Having port 27017 available from the host for local development with mongodb tools
        ports:
            - 27017:27017
    pp-cron: #Also acts as a leader for distributed tasks it schedules and distributes to workers.
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/cron/Dockerfile
        image: pp-cron
        environment:
            - MONGODB_CONNECTION_STRING=${API_MONGODB_CONNECTION_STRING}
            - CURRENCY_BEACON_API_TOKEN=${CRON_CURRENCY_BEACON_API_TOKEN}
            - SCRAPEOPS_API_KEY=${CRON_SCRAPEOPS_API_KEY}
            - BABEL_DISABLE_CACHE=1
            - DO_SCRAPING=${CRON_DO_SCRAPING}
        volumes:
            - pp-cron-node_modules:/app/node_modules
            - ./cron:/app
        expose:
            - 8000
        depends_on:
            - pp-db
    pp-product-scraper: #worker which registers itself with the pp-cron leader.
        build:
            context: .
            dockerfile: ./docker/product-scraper/Dockerfile
        image: pp-product-scraper
        environment:
            - LEADER_HOST=pp-cron
            - LEADER_PORT=8000
        volumes:
            - pp-product-scraper-node_modules:/app/node_modules
            - ./product-scraper:/app
        expose:
            - 8000
        depends_on:
            - pp-cron #because pp-cron is our cluster leader.

volumes:
    pp-mongodb:
        name: pp-mongodb
    pp-react-node_modules:
        name: pp-react-node_modules
    pp-api-node_modules:
        name: pp-api-node_modules
    pp-cron-node_modules:
        name: pp-cron-node_modules
    pp-product-scraper-node_modules:
        name: pp-product-scraper-node_modules
