version: "3"

services:
    pp-react-nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/react-nginx/Dockerfile
            target: dev
        image: pp-react-nginx
        environment:
            - PORT=${REACT_NGINX_PORT}
            - BROWSER=${REACT_NGINX_BROWSER}
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - pp-node_modules:/app/react/node_modules
            - ./react:/app/react
        ports:
            - 3000:3000
        depends_on:
            - pp-api
    pp-api:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        image: pp-api
        environment:
            - MONGODB_CONNECTION_STRING=${BACKEND_MONGODB_CONNECTION_STRING}
        expose:
            - 5000
        depends_on:
            - pp-db
        command: "npm start"
    pp-db:
        restart: unless-stopped
        build:
            context: ./docker/db
        image: pp-db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${DB_MONGO_INITDB_DATABASE}
        volumes:
            - pp-mongodb:/data/db
        expose:
            - 27017

volumes:
    pp-mongodb:
        name: pp-mongodb
    pp-node_modules:
        name: pp-node_modules