server {
    listen 80;
    server_name _;
    server_tokens off;

    client_max_body_size 20M;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # Try loading files from locally if possible(aka we're on a prod build)
        # If we can't load files from locally, we're on a dev build. proxy to the react container
        try_files $uri /index.html @pp-react;
    }

    location @pp-react {
        proxy_set_header Host $host;
        resolver 127.0.0.11 valid=30s;
        set $target "http://pp-react:3000"; #Some magic. Makes sure nginx doesn't crash if the upstream isn't found(This won't be found in prod)
        proxy_pass $target;
    }

    location /api {
        proxy_set_header Host $host;
        proxy_pass http://pp-api:5000/api;
    }

}