db.products.insertMany([
	{
		url: "https://www.bordergold.com/product/1-oz-2022-canadian-gold-maple-leaf-coin/",
		title: "1 oz 2022 Canadian Gold Maple Leaf Coin",
		productType: "gold",
		productSpecifics: ["government_issued", "9999"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/2022-canadian-gold-maple-leaf-1-oz-9999/",
		title: "2022 Canadian Gold Maple Leaf 1 oz .9999",
		productType: "gold",
		productSpecifics: ["government_issued", "9999"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-2022-canadian-silver-maple-leaf-coin/",
		title: "1 oz 2022 Canadian Silver Maple Leaf Coin",
		productType: "silver",
		productSpecifics: ["government_issued", "9999"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/2022-canadian-silver-maple-leaf-1-oz-9999/",
		title: "2022 Canadian Silver Maple Leaf 1 oz .9999",
		productType: "silver",
		productSpecifics: ["government_issued", "9999"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-platinum-maple-leaf/",
		title: "1 oz Canadian Maple Leaf Platinum Coin (Random Year)",
		productType: "platinum",
		productSpecifics: ["government_issued", "9995"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/2022-platinum-maple-leaf-1-oz-9995/",
		title: "2022 Platinum Maple Leaf 1 oz .9995",
		productType: "platinum",
		productSpecifics: ["government_issued", "9995"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/10-oz-rcm-silver-bar/",
		title: "10 oz RCM Silver Bar (Pre-Sale: 2 Week Delivery)",
		productType: "silver",
		productSpecifics: ["government_issued", "9999"],
		weight: 311.04,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/silver-bar-10-oz-royal-canadian-mint-9999/",
		title: "Silver Bar Royal Canadian Mint 10 oz .9999",
		productType: "silver",
		productSpecifics: ["government_issued", "9999"],
		weight: 311.04,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/100-oz-rcm-silver-bar/",
		title: "100 oz RCM Silver Bar (Pre-Sale: 2 Week Delivery)",
		productType: "silver",
		productSpecifics: ["government_issued", "9999"],
		weight: 3110.35,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/silver-bar-100-oz-royal-canadian-mint-9999/",
		title: "Silver Bar Royal Canadian Mint 100 Oz .9999 (New Design)",
		productType: "silver",
		productSpecifics: ["government_issued", "9999"],
		weight: 3110.35,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/10-oz-gold-bar/",
		title: "10 Oz Gold Bar",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 311.04,
		mint: "various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/misc-branded-gold-bar-10-oz-9999/",
		title: "Misc. Branded Gold Bar 10 oz .9999",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 311.04,
		mint: "various",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/5-gram-gold-bar/",
		title: "5 Gram Gold Bar (Pre-Sale: 2 Week Delivery)",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 5,
		mint: "various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/perth-mint-gold-bar-5-gram/",
		title: "PAMP Suisse Gold Bar, 5 Gram .9999",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 5,
		mint: "PAMP Suisse",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/10-gram-gold-bar/",
		title: "10 Gram Gold Bar",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 10,
		mint: "various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/pamp-suisse-gold-bar-10-gram/",
		title: "PAMP Suisse Gold Bar, 10 Gram .9999",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 10,
		mint: "PAMP Suisse",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-platinum-bar/",
		title: "1 oz Platinum Bar",
		productType: "platinum",
		productSpecifics: ["not_government_issued", "9995"],
		weight: 31.1,
		mint: "various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/pamp-suisse-lady-fortuna-platinum-bar-1-oz-9995/",
		title: "PAMP Suisse Lady Fortuna Platinum Bar 1 oz .9995",
		productType: "platinum",
		productSpecifics: ["not_government_issued", "9995"],
		weight: 31.1,
		mint: "PAMP Suisse",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-gold-bar/",
		title: "1 oz Gold Bar",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 31.1,
		mint: "various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/credit-suisse-gold-bar-1-oz-9999/",
		title: "Credit Suisse Gold Bar 1 oz .9999",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 31.1,
		mint: "Credit Suisse",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-kilo-pamp-silver-bar/",
		title: "1 Kilo PAMP Silver Bar",
		productType: "silver",
		productSpecifics: ["not_government_issued", "999"],
		weight: 1000,
		mint: "PAMP Suisse",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/silver-valcambi-suisse-cast-1-kilo-bar-999/",
		title: "Silver Valcambi Suisse 1 Kilo Cast Bar .999",
		productType: "silver",
		productSpecifics: ["not_government_issued", "999"],
		weight: 1000,
		mint: "Valcambi Suisse",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-silver-britannia/",
		title: "1 oz. Silver Britannia",
		productType: "silver",
		productSpecifics: ["government_issued", "999"],
		weight: 31.1,
		mint: "The Royal Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/2022-great-britain-silver-britannia-1-oz-999/",
		title: "2022 Great Britain Silver Britannia 1 oz .999",
		productType: "silver",
		productSpecifics: ["government_issued", "999"],
		weight: 31.1,
		mint: "The Royal Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/5-oz-silver-bar/",
		title: "5 oz Silver Bar (Pre-Sale: 4 Week Delivery)",
		productType: "silver",
		productSpecifics: ["not_government_issued", "999"],
		weight: 155.52,
		mint: "various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/silver-argentia-precious-metals-cast-bar-5-oz-9999/",
		title: "Silver Argentia Precious Metals Cast Bar, 5 oz .9999",
		productType: "silver",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 155.52,
		mint: "Argentia Precious Metals",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	}
]);

db.createCollection("spot", {
	timeseries: {
		timeField: "timestamp",
		granularity: "hours",
	},
});
