db.products.insertMany([
	{
		url: "https://canadianpmx.com/product/misc-dated-backdated-canadian-gold-maple-leaf-1-oz-9999/",
		productType: "gold",
		productSpecifics: ["government_issued", "9999"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-2022-canadian-gold-maple-leaf-coin/",
		productType: "gold",
		productSpecifics: ["government_issued", "9999"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/credit-suisse-gold-bar-1-oz-9999/",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 31.1,
		mint: "Credit Suisse",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-gold-bar/",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 31.1,
		mint: "Credit Suisse",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/misc-branded-gold-bar-1-kilogram-999-32-15-tr-oz/",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 1000,
		mint: "various",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/kilo-gold-bar/",
		productType: "gold",
		productSpecifics: ["not_government_issued", "9999"],
		weight: 1000,
		mint: "various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
]);
