db.products.insertMany([
	{
		url: "https://www.bordergold.com/product/1-oz-2023-canadian-gold-maple-leaf-coin/",
		title: "1 oz 2023 Canadian Gold Maple Leaf Coin",
		productType: ["gold"],
		purities: ["9999"],
		issuance: ["government_issued"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/2023-canadian-gold-maple-leaf-1-oz-9999/",
		title: "2023 Canadian Gold Maple Leaf 1 oz .9999",
		productType: ["gold"],
		purities: ["9999"],
		issuance: ["government_issued"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-2022-canadian-silver-maple-leaf-coin/",
		title: "1 oz 2022 Canadian Silver Maple Leaf Coin",
		productType: ["silver"],
		purities: ["9999"],
		issuance: ["government_issued"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/2023-canadian-silver-maple-leaf-1-oz-9999-available-for-pre-order/",
		title: "2023 Canadian Silver Maple Leaf 1 oz .9999",
		productType: ["silver"],
		purities: ["9999"],
		issuance: ["government_issued"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-platinum-maple-leaf/",
		title: "1 oz Canadian Maple Leaf Platinum Coin (Random Year)",
		productType: ["platinum"],
		purities: ["9995"],
		issuance: ["government_issued"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/2023-platinum-maple-leaf-1-oz-9995/",
		title: "2023 Platinum Maple Leaf 1 oz .9995",
		productType: ["platinum"],
		purities: ["9995"],
		issuance: ["government_issued"],
		weight: 31.1,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/10-oz-rcm-silver-bar/",
		title: "10 oz RCM Silver Bar",
		productType: ["silver"],
		purities: ["9999"],
		issuance: ["government_issued"],
		weight: 311.04,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/silver-bar-10-oz-royal-canadian-mint-9999/",
		title: "Silver Bar Royal Canadian Mint 10 oz .9999",
		productType: ["silver"],
		purities: ["9999"],
		issuance: ["government_issued"],
		weight: 311.04,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/100-oz-rcm-silver-bar/",
		title: "100 oz RCM Silver Bar",
		productType: ["silver"],
		purities: ["9999"],
		issuance: ["government_issued"],
		weight: 3110.35,
		mint: "Royal Canadian Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/silver-bar-100-oz-royal-canadian-mint-9999/",
		title: "Silver Bar Royal Canadian Mint 100 Oz .9999 (New Design)",
		productType: ["silver"],
		purities: ["9999"],
		issuance: ["government_issued"],
		weight: 3110.35,
		mint: "Royal Canadian Mint",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/10-oz-gold-bar/",
		title: "10 oz Gold Bar",
		productType: ["gold"],
		purities: ["9999"],
		issuance: ["not_government_issued"],
		weight: 311.04,
		mint: "Various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/5-gram-gold-bar/",
		title: "5 gram Gold Bar",
		productType: ["gold"],
		purities: ["9999"],
		issuance: ["not_government_issued"],
		weight: 5,
		mint: "Various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/perth-mint-gold-bar-5-gram/",
		title: "PAMP Suisse Gold Bar, 5 Gram .9999100",
		productType: ["gold"],
		purities: ["9999"],
		issuance: ["not_government_issued"],
		weight: 5,
		mint: "PAMP Suisse",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/10-gram-gold-bar/",
		title: "10 Gram Gold Bar",
		productType: ["gold"],
		purities: ["9999"],
		issuance: ["not_government_issued"],
		weight: 10,
		mint: "Various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/pamp-suisse-gold-bar-10-gram/",
		title: "PAMP Suisse Gold Bar, 10 Gram .9999",
		productType: ["gold"],
		purities: ["9999"],
		issuance: ["not_government_issued"],
		weight: 10,
		mint: "PAMP Suisse",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-platinum-bar/",
		title: "1 oz Platinum Bar",
		productType: ["platinum"],
		purities: ["9995"],
		issuance: ["not_government_issued"],
		weight: 31.1,
		mint: "Various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-gold-bar/",
		title: "1 oz Gold Bar (Various Refiners)",
		productType: ["gold"],
		purities: ["9999"],
		issuance: ["not_government_issued"],
		weight: 31.1,
		mint: "Various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-kilo-pamp-silver-bar/",
		title: "1 Kilo PAMP Silver Bar",
		productType: ["silver"],
		purities: ["999"],
		issuance: ["not_government_issued"],
		weight: 1000,
		mint: "PAMP Suisse",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/1-oz-silver-britannia/",
		title: "1 oz. Silver Britannia",
		productType: ["silver"],
		purities: ["999"],
		issuance: ["government_issued"],
		weight: 31.1,
		mint: "The Royal Mint",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://www.bordergold.com/product/5-oz-silver-bar/",
		title: "5 oz Silver Bar",
		productType: ["silver"],
		purities: ["999"],
		issuance: ["not_government_issued"],
		weight: 155.52,
		mint: "Various",
		dealer: "Border Gold",
		pricing_last_updated: 0,
		pricing: null,
	},
	{
		url: "https://canadianpmx.com/product/silver-argentia-precious-metals-cast-bar-5-oz-9999/",
		title: "Silver Argentia Precious Metals Cast Bar, 5 oz .9999",
		productType: ["silver"],
		purities: ["9999"],
		issuance: ["not_government_issued"],
		weight: 155.52,
		mint: "Argentia Precious Metals",
		dealer: "CanadianPMX",
		pricing_last_updated: 0,
		pricing: null,
	},
]);

db.spot.insertMany([
	{
		symbol: 'AG',
		price: {
			"CAD": 0,
			"USD": 0
		},
		updatedAt: null
	},
	{
		symbol: 'AU',
		price: {
			"CAD": 0,
			"USD": 0
		},
		updatedAt: null
	},
	{
		symbol: 'PD',
		price: {
			"CAD": 0,
			"USD": 0
		},
		updatedAt: null
	},
	{
		symbol: 'PT',
		price: {
			"CAD": 0,
			"USD": 0
		},
		updatedAt: null
	}
]);

db.createCollection("subscriptions");