user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    # Real IP Module Configuration. Cloudflare IPs listed at https://www.cloudflare.com/ips-v4/# and https://www.cloudflare.com/ips-v6/#
    # nginx-with-certcheck.sh updates these on start and every 6 hours.
    #set_real_ip_from dummy_ip_will_be_replaced_dynamically;
    #set_real_ip_from dummy_ip_will_be_replaced_dynamically;
    #set_real_ip_from dummy_ip_will_be_replaced_dynamically;
    #real_ip_header X-Forwarded-For; #Note: this line will be replaced by the script as well.

    include /etc/nginx/conf.d/*.conf;
}