name: ci

on:
    push:
        branches:
            - "main"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Azure Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ secrets.AZURECR_SERVER }}
                  username: ${{ secrets.AZURECR_USERNAME }}
                  password: ${{ secrets.AZURECR_PASSWORD }}
            - name: Build and push react-nginx
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  file: "./docker/react-nginx/Dockerfile"
                  tags: |
                      ${{ secrets.AZURECR_SERVER }}/react-nginx:latest
            - name: Build and push api
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  file: "./docker/api/Dockerfile"
                  tags: |
                      ${{ secrets.AZURECR_SERVER }}/api:latest
            - name: Build and push cron
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  file: "./docker/cron/Dockerfile"
                  tags: |
                      ${{ secrets.AZURECR_SERVER }}/cron:latest
